### ISSUE TITLE
Ignore numbers and non-Devanagari characters function

### ISSUE THREAD

**Issue by gasyoun** [anubhav-chattoraj/indic-tools#17]
Here is a part of my reverse dictionary of Sanskrit after my reverse php script sorted it.

 अ
I अजिम्ःअ
H अचिन्तिअ
P इन्दिअ
N उत्सङ्ग्३अ
आ
N पऋआ
N घूर्णिआ
फुम्फुआ
इ
M आइ
रेउइ
M अच्छाइ
M दादाभाइ
M नाह्नाभाइ
राजसाइ
ई
G हूङ्गराई
I सुभ्रुई
R विकृई
I धृतराष्टृई
G धोई
उ

If I do not click "Ignore numbers and non-Devanagari characters" I get
I अजिम्ःअ
M अच्छाइ
H अचिन्तिअ
रेउइ
राजसाइ
फुम्फुआ

If I click the checkbox, I get:

ई
इ
आ
G हूङ्गराई
I सुभ्रुई
R विकृई

Does the checkbox works as intended? If so I hardly understand what and where does it ignore, thanks.

**Comment by anubhav-chattoraj** [comment]
It's the space after the Roman letter which is giving you trouble. The option doesn't ignore spaces; type a space manually in the "ignore these characters" textbox, and they should sort fine. (I do recognize that the user interface could be more helpful in this regard.)

**Comment by gasyoun** [comment]
Getting closer. When I try to sort (that has been already sorted with <a href="https://github.com/drdhaval2785/SanskritNLP/blob/master/sanskritsorting/reverse11.php">Dhaval's reverser</a>) http://pastebin.com/eN25agx4 in ascending retrograde I get "G bhaṛ" above "ūṃṃ". Should not it go a bit closer with "M upaṛ" together? I get http://pastebin.com/LKEWE8eu - seems fishy.

**Comment by anubhav-chattoraj** [comment]
Can't reproduce. This is the output I get for your input file:
- [not ignoring spaces](http://pastebin.com/T0YNJ9cq)
- [ignoring spaces](http://pastebin.com/tUyUSehS)
