### ISSUE TITLE
Non-Devanagari sorting broken

### ISSUE THREAD

**Issue by anubhav-chattoraj** [anubhav-chattoraj/indic-tools#22]
All Roman letters seem to be treated as equivalent, even when "ignore non-Devanagari characters" is unchecked. 

Input such as 

```
b
a
c
```

outputs

```
b
a
c
```

**Comment by gasyoun** [comment]
Solvable?

**Comment by anubhav-chattoraj** [comment]
Almost certainly. I'll look at it this weekend.

**Comment by anubhav-chattoraj** [comment]
Fixed by commit dddc860. 

Non-Devanagari sorting should be working now.
